export const SET_USER_AUTH_TOKEN = "SET_USER_AUTH_TOKEN";
export const SET_USER_LOGOUT = "SET_USER_LOGOUT";
export const SET_NOTIFICATION = "SET_NOTIFICATION";
export const SET_REMOVE_NOTIFICATION = "SET_REMOVE_NOTIFICATION";